.\" Manpage for sneakers.
.\" Author of this manpage is Ferdinand Thiessen <rpm@fthiessen>, contact him to correct errors or typos.
.\" This man page is released into the public domain, see also https://creativecommons.org/publicdomain/zero/1.0/
.TH sneakers 6 "17 February 2017" "1.0" "sneakers User Manual"
.SH NAME
sneakers
.SH SYNOPSIS
sneakers
.SH DESCRIPTION
sneakers recreates the famous data decryption effect with
the same content seen on screen in the 1992 hacker movie Sneakers.
.SH "SEE ALSO"
nms(6)
.SH AUTHOR
Brian Barto ( https://github.com/bartobri )
.SH COPYRIGHT
sneakers is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
