name: nms
version: 0.2.1
summary: no-more-secrets
description: pipe text through the nms binary to create a visual effect similar to that seen in the movie "Sneakers"
confinement: strict

apps:
        nms:
                command: nms.sh
        sneakers:
                command: sneakers.sh

parts:
        nms:
                plugin: make
                source: https://github.com/bartobri/no-more-secrets.git
                build-packages:
                        - libncurses5-dev
                        - libncursesw5-dev
                        - build-essential
                stage-packages:
                        - libncurses5
                        - libncursesw5
                        - console-setup-linux
                        - locales
                        - libc-bin
        wrapper:
                plugin: dump
                source: usr
